language: java
install: true
jdk:
- oraclejdk8
script:
- "./gradlew build -x signArchives -s"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/modules-2/"
  - "$HOME/.gradle/wrapper/dists/"
notifications:
  slack:
      rooms:
          - uhg-pilot:96HfPhnzzUA8UwhXREzb3F3T#atc-giraffle
